name: infra-storage-longhorn
apiVersion: v2
version: 0.1.0
description: A Helm chart for deploying longhorn storage
type: application
appVersion: 0.1.0
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - monitoring
  - storage
  - s3
  - homelab
dependencies:
  - name: longhorn
    version: 1.10.1
    repository: https://charts.longhorn.io
  - name: edge-access
    version: 0.1.0
    repository: https://karafrorg.github.io/edge-access
