longhorn:
  preUpgradeChecker:
    jobEnabled: false
    upgradeVersionCheck: false
  metrics:
    serviceMonitor:
      enabled: false
  longhornManager:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    log:
      format: json
  longhornDriver:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    log:
      format: json
  longhornUI:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
    log:
      format: json
  database:
    image: postgres:17
    secretRef:
      name: postgres-longhorn-secret
    databaseName: longhorn
    port: 5342
    appName: postgres
    volumes:
      mountName: postgres-longhorn-volume
      mountPath: /var/lib/ghost/content
      claimName: postgres-longhorn-pvc
      claimSize: 10Gi
  defaultSettings:
    deletingConfirmationFlag: true
