name: infra-storage-seaweedfs
apiVersion: v2
version: 0.1.0
description: A Helm chart for deploying CEPH storage
type: application
appVersion: 0.1.0
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - monitoring
  - storage
  - s3
  - homelab
dependencies:
  - name: rook-ceph
    version: 1.19.0
    repository: https://charts.rook.io/release
