apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: primary-object-store
spec:
  metadataPool:
    replicated:
      size: 3
  dataPool:
    replicated:
      size: 3
  preservePoolsOnDelete: false
  gateway:
    port: 8000
    instances: 1
