apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: primary-object-store
spec:
  gateway:
    instances: 1
    port: 80
  dataPool:
    replicated:
      size: 2
  metadataPool:
    replicated:
      size: 2
