apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: primary-object-store
spec:
  gateway:
    instances: 1
  dataPool:
    replicated:
      size: 3
  metadataPool:
    replicated:
      size: 3
