apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: default-object-store
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 8
      codingChunks: 4
    parameters:
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 1
