{{- range $user := .Values.cephObjectStoreUsers  }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ${{ $user.displayName }}-objectstore-creds
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: gcp-sm-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $user.displayName }}-objectstore-creds
  data:
    - match:
        secretKey: AccessKey
        remoteRef:
          remoteKey: infra/tempo/s3
          property: access_key
    - match:
        secretKey: SecretKey
        remoteRef:
          remoteKey: infra/tempo/s3
          property: secret_key
{{- end}}