apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: objectstore-ingress-certificate
spec:
  secretName: objectstore-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - objectstore.karafra.net
