apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: objectstore-public-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-ingress-gateway
      namespace: infra-network
  hostnames:
    - objectstore.karafra.net
  rules:
    - backendRefs:
        - group: networking.istio.io
          kind: VirtualService
          name: objectstore-virtual-service
          port: 8333
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
