apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: objectstore-public-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-ingress-gateway
      namespace: infra-network
  hostnames:
    - objectstore.karafra.net
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: seaweedfs-s3
          port: 8333
