apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seaweed-admin-public-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-ingress-gateway
      namespace: infra-network
  hostnames:
    - seaweed.karafra.net
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: seaweedfs-admin
          port: 23646
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
