apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.longhorn.database.volumes.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.longhorn.database.volumes.claimSize }}
